api_platform:
    title: 'ALLAN API'
    version: '1.0.0'
    show_webby: false
    defaults:
        pagination_items_per_page: 100
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
